### PR TITLE
Fix decode acl connection handle

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by alexmoon** [comment]
I think this change is correct, but I would note that by the spec handles with bit 11 set are reserved and not allowed. Are you running into controllers that generate handles using bit 11?

**Comment by lulf** [comment]
I don't see where bit 11 is not allowed set, could you point me to it? In https://www.bluetooth.com/wp-content/uploads/Files/Specification/HTML/Core-54/out/en/host-controller-interface/host-controller-interface-functional-specification.html#UUID-eee7884c-c6d1-159a-9fc2-aebf6bcf30e7, for the 'connection handle' value, it is specified that the valid _range_ for a connection handle is 0 - 0xeff. The value 0xeff does have bit 11 set (0xeff == 0b111011111111).

**Comment by alexmoon** [comment]
Oh whoops! You're right. My mistake.

**Comment by lulf** [comment]
No worries, I had to stare at the spec and the code a lot before finding the issue :rofl:

**Pull request merged**
